## Hello IPython

In [1]:
print 'hello, Alex'

hello, Alex


In [4]:
x = 3
print x

3


In [8]:
x += 5
x

23

In [10]:
my_string = 'adhjhkjh'
my_string

'adhjhkjh'

In [11]:
12 + 45

57

In [12]:
24 * 3.5

84.0

## Lists, Dictionaries

In [13]:
x = [1, 2, 3]

In [16]:
x[0], x[2]

(1, 3)

In [21]:
y = x[:2] + [5, 10]
y

[1, 2, 5, 10]

In [24]:
y[::2]

[1, 5]

In [25]:
y[::-1]

[10, 5, 2, 1]

## Dicts

In [26]:
d = {'a': 1, 'b': 2}

In [32]:
d['c'] = 3
d['casdsd'] = 34
d

{'a': 1, 'b': 2, 'c': 3, 'casdsd': 34}

In [33]:
for key, value in d.items():
    print key, value

a 1
c 3
b 2
casdsd 34


 - numpy (numerics) + scipy (functions) 
 - matplotlib - plotting
 - pandas - convenient operations on data for DS
 - scikit-learn - ML

## Hello, numpy

In [34]:
import numpy

In [43]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
x.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [44]:
x[:4]

array([0, 1, 2, 3])

In [46]:
print x[:3]
print x[3:7]
print x[7:]

[0 1 2]
[3 4 5 6]
[7 8 9]


### Vector ops

In [42]:
x = numpy.arange(10 ** 6)
%timeit 3 * x + 12.

100 loops, best of 3: 6.45 ms per loop


In [47]:
Z = numpy.arange(15).reshape(5, 3)
Z

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [49]:
numpy.log(numpy.exp(Z))

array([[  0.,   1.,   2.],
       [  3.,   4.,   5.],
       [  6.,   7.,   8.],
       [  9.,  10.,  11.],
       [ 12.,  13.,  14.]])

In [50]:
Z += 4

In [51]:
Z

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [55]:
Z[::2, :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [58]:
Z.sum(axis=1)

array([15, 24, 33, 42, 51])

In [59]:
Z.sum(axis=0)

array([50, 55, 60])

In [71]:
Z.max(axis=1)

array([ 6,  9, 12, 15, 18])

In [74]:
Z2 = - Z
Z2.sort(axis=1)
Z2

array([[ -6,  -5,  -4],
       [ -9,  -8,  -7],
       [-12, -11, -10],
       [-15, -14, -13],
       [-18, -17, -16]])

In [61]:
Z[[0, 2, 4], :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

## indexing with boolean array

In [63]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [69]:
x[x < 7.4]

array([0, 1, 2, 3, 4, 5, 6, 7])

## Copies

In [81]:
x = numpy.arange(10)
y = x[:5].copy()
print x, y
y[4] = 10
print x, y

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9] [ 0  1  2  3 10]


In [82]:
numpy.random.normal(loc=2, scale=12, size=10000)

array([ 29.87106868,   1.48812383,   4.61406417, ...,  -7.62578366,
        16.05328271,   3.29466941])

## Exercise

0. import numpy
1. sample from normal distribution 1000 elements
2. leave only positive numbers
3. count number of left numbers, std, min, max, mean

In [85]:
x.shape

(10,)

In [ ]:
x.arg

In [ ]:
numpy.sin()

In [90]:
x = numpy.random.normal(size=10000)
y = x[x > 0]
y.min(), y.max(), y.std(), y.mean(), y.shape

(0.00044950888224008637,
 3.5780563068443154,
 0.61072462596428589,
 0.7958258421168346,
 (4992,))